spring.application.name=personal-loan

#数据库连接信息
spring.datasource.url=jdbc:mysql://localhost:3306/personal_loan?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=438123zff.

#JPA配置
spring.jpa.hibernate.ddl-auto=update
#显示SQL
spring.jpa.show-sql=true
#格式化SQL
spring.jpa.properties.hibernate.format_sql=true

#配置mybatis
#mybatis.mapper-locations=classpath*:mapper/*.xml

mybatis.configuration.map-underscore-to-camel-case=true

