spring:
    application:
        name: demo
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db01?useSSL=false
        username: root
        password: 123456



server:
    port: 8080
    servlet:
        context-path: /demo

example:
    value: Hello World!

